language: node_js
sudo: false
node_js:
- '4'
- '5'
- '6'
script: npm test
notifications:
  irc:
    channels:
    - irc.mozilla.org#amo-bots
    on_success: change
    on_failure: always
after_script:
- cat ./coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: npm
  email: addons-dev-automation+npm@mozilla.com
  skip_cleanup: true
  api_key:
    secure: mE50ML7MM+iQu2PvtVdhX01Y/Ja+438wqxIHk1NKp+mhxKl2SMc652RzNyftyCxNsAFa1+YUWSJxGJAq5hDYTGRLtrzpfhZezhFSSP63HvDom10OW4YRfHzvZBKeXrA13rH077tl02gmXYm1fbVoBjkQ4DJggiq5jFOEnBcKM/vGFmdKmpMIzcnYiJ06+5OlengkvqGKrowywMRD1LvZb4L90gLUMs4jVCmywbXmqmQIjNtQaSA5nKLVtMlG1pGP2QAGWY8ZLa4P67hCttxLEOZ1MVc/dme6Ev09jtUfFNlLCMLO/pjJYfRV8VTOCL6lthTzA+FFy3ypCrC5mQb27GDq8kpVRkonDegoqw5MM5XTRr1kg+IihZ6ZRuebprq5B85rrjhDouQJvDl7nN6pCTSizs96Npz1OTsrjn+F3OCqeyLKOuw10kIR8/cBYTXb8A4m8AvBaYPF7d3s2LiybFdYdWOY+Hjr2j22uozY496GcCtvh7cM9ec1bGegFq7/pUfT9y02mpQsi4d6wS0Y7Kwca3Kx1RiH40zLIz/UbrHuxzwU4ABuEy59z39EIg174S9B3F5CKQRsse2xot/8bLQk0aGumqzEeEoS0rFnWW1yuQjqPuL58euDVvo7w5H498iXEozE0A4sgkwslCmnh73IOudPhGCIW7g+IzAkdaY=
  on:
    tags: true
    repo: mozilla/dispensary
    branch: master
